services:
  app:
    build: .
    image: guardias2-app
    container_name: guardias2-app
    ports:
      - "8084:8080"
    volumes:
      - guardias2-uploads:/app/uploads
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-soft-term-apur2p4j-pooler.c-7.us-east-1.aws.neon.tech/neondb?ssl=true&sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_WmdS1V5PrLGg
      - JWT_SECRET=D6$$PG38^RDbQXu%4^J8XmpfP4!i9apBh
    restart: unless-stopped

volumes:
  guardias2-uploads:
