# Ativa o perfil de desenvolvimento
spring.profiles.active=prod

# Configurações do Banco Neon (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-soft-term-apur2p4j-pooler.c-7.us-east-1.aws.neon.tech/neondb?ssl=true&sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_WmdS1V5PrLGg}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Segurança - JWT
jwt.secret=${JWT_SECRET:D6$PG38^RDbQXu%4^J8XmpfP4!i9apBh}
jwt.expiration=86400000

# Diretório de Uploads
app.upload.dir=uploads/

# Configuração Hikari para manter a conexão estável com o Neon
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.connection-test-query=SELECT 1

# Define o tamanho máximo permitido para cada arquivo individual
spring.servlet.multipart.max-file-size=50MB

# Define o tamanho máximo total permitido para a requisição inteira
spring.servlet.multipart.max-request-size=50MB

#Cloudinary
cloudinary.cloud-name=rmrarw6x
cloudinary.api-key=439349474216427
cloudinary.api-secret=9VU_hL0GPCDxpoBxEG9si_soF2k