spring.datasource.url=jdbc:postgresql://ep-soft-term-apur2p4j-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=:npg_XPzEt9DsbxA6
spring.datasource.driver-class-name=org.postgresql.Driver

# Forçar o dialeto resolve o problema de metadados:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=abc123
jwt.expiration=86400000