
spring.datasource.url="jdbc:postgresql://neondb_owner:npg_3SHJuBX4VGNk@ep-soft-term-apur2p4j-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

spring.datasource.username=neondb_owner
spring.datasource.password=npg_3SHJuBX4VGNk
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true